name: 'srl_propbank'
datadir: '../../dataset/propbank'
train_file: 'train.jsonl'
val_file: 'val.jsonl'
test_file: 'test.jsonl'
roles_file: 'unique_roles.json'
max_seq_len: 64
embedding_model: 'FacebookAI/xlm-roberta-base'
embedding_dim: 768
pin_memory: True

